name: inthzarapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  simple_tooltip: ^0.1.16
  page_view_indicators: ^1.4.0
  flutter_rating_bar: ^3.2.0+1
  font_awesome_flutter: ^8.10.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - leading.png
    - 1.jpg
    - logo.png
    - bio.png
    - recfly.png
    - all.png
    - rstnd.png
    - amb.png
    - school.png
    - travels.png
    - us2.png
    - vell.png
    - job.png
    - hypermart.png
    - hospitals.png
    - fab.png
    - 2.png
    - 4.png
    - gg.png
    - fb.png
    - image.png
    - img.png
    - drag_item.svg
    - icon_home.png
    - med.png
    - vec.png
    - bpo.png
    - bank.png
    - call.png
    - drvr.png
    - finance.png
    - hotel.png
    - it.png
    - jvl.png
    - 111.svg
    - demo_hotel.png
    - demo_hotell.png
    - hotel_sharp.png
    - hotel_sharp_two.png
    - google_map.png
    - rect.png
    - imagw.png
    - imagi.png
    - imagl.png
    - imagf.png
    - user_rest.png
    - user_rest1.png
    - user_rest1.png
    - rect_back.png
    - electrician.png
    - plumber.png
    - acser.png
    - paint.png
    - cleanig.png
    - car.png
    - pest.png
    - sal.png
    - itpro.png
    - rect_plan.png
    - payment_option.png
    - razor_pay.png
    - jobs_img.png
    - rect_image.png
    - net.png
    - nodata.png
    - nonotifications.png
    - nodatafount.png
    - locationw.png
    - electriii.png
    - furniture.png
    - reply.png
    - outline_work.png
    - outline_call.png
    - outline_location.png
    - outline_add.png
    - outline_brightness.png
    - whats.png
    - fac.png
    - insta.png
    - link.png
    - semi.png
    - tnku.png
    - h1.png
    - h2.png
    - h3.png
    - h4.png
    - h5.png
    - h6.png
    - h7.png
    - h8.png
    - h10.png
    - h11.png
    - h12.png





  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
